Repository contentauth/c2patool, pull requests merged in 2024-08, with the labels that each got.

#221 Remove rust toolchain version lock
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement, safe to test

#222 Update to latest c2pa SDK
  Cargo.lock
  Cargo.toml
Labels: accepted, safe to test, good to test

#230 Initial fragment support
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: safe to test
